name: Pull request to Develop

on:
  push:
    branches:
      - develop
    # types:
    #   - opened
    #   - synchronize
    #   - reopened

jobs:
  check_code:
    name: Check code quality and coverage
    runs-on: ubuntu-latest
    steps:
      - name: Python linter
        id: pylint
        uses: docker://reasonsoftware/action-pylint:v2
    